name: Main workflow
on:
    push:
        branches:
            - source
jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
        - name: 同步当前分支文件
          uses: actions/checkout@v1
        - name: 配置环境
          uses: actions/setup-node@v1
          with:
           node-version: 12.x
        - name: 配置发布公钥&发布
          run: |
            mkdir -p ~/.ssh/
            echo "$RSA_TOKEN" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            git config --global user.name 'zkytech'
            git config --global user.email 'zhangkunyuan@hotmail.com'
          run: |
            npm i -g hexo-cli
            npm i
            hexo generate && hexo deploy
            scp -r public root@zkytech.top:/var/www/blog
          env:
            RSA_TOKEN: ${{ secrets.GH_ACTION_DEPLOY_KEY }}