name: Main workflow
on:
    push:
        branches:
            - source
jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
        - name: 同步当前分支文件
          uses: actions/checkout@v1
        - name: 同步子模块
          run: git submodule update --init --recursive
        - name: 配置环境
          uses: actions/setup-node@v1
          with:
           node-version: 12.x
        - name: 发布
          run: |
            mkdir -p ~/.ssh/
            echo "$RSA_TOKEN" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-keyscan e.coding.net >> ~/.ssh/known_hosts
            ssh-keyscan zkytech.top >> ~/.ssh/known_hosts
            export HEXO_ALGOLIA_INDEXING_KEY="$ALGOLIA_ADMIN_API_KEY"
            git config --global user.name 'zkytech'
            git config --global user.email 'zhangkunyuan@hotmail.com'
            npm i -g hexo-cli
            npm i
            hexo generate && hexo deploy
            ssh root@zkytech.top "rm -rf /var/www/blog"
            scp -r public root@zkytech.top:/var/www/blog
          env:
            RSA_TOKEN: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
            ALGOLIA_ADMIN_API_KEY: ${{secrets.ALGOLIA_ADMIN_API_KEY}}
